/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ContractorRouteImport } from './routes/contractor'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GovernmentRouteImport } from './routes/government'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as ProblemRouteImport } from './routes/problem'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SolutionRouteImport } from './routes/solution'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as WorkflowRouteImport } from './routes/workflow'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorRoute = ContractorRouteImport.update({
  id: '/contractor',
  path: '/contractor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentRoute = GovernmentRouteImport.update({
  id: '/government',
  path: '/government',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemRoute = ProblemRouteImport.update({
  id: '/problem',
  path: '/problem',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionRoute = SolutionRouteImport.update({
  id: '/solution',
  path: '/solution',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/citizen': typeof CitizenRoute
  '/contact': typeof ContactRoute
  '/contractor': typeof ContractorRoute
  '/dashboard': typeof DashboardRoute
  '/government': typeof GovernmentRoute
  '/impact': typeof ImpactRoute
  '/problem': typeof ProblemRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solution': typeof SolutionRoute
  '/technology': typeof TechnologyRoute
  '/workflow': typeof WorkflowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/citizen': typeof CitizenRoute
  '/contact': typeof ContactRoute
  '/contractor': typeof ContractorRoute
  '/dashboard': typeof DashboardRoute
  '/government': typeof GovernmentRoute
  '/impact': typeof ImpactRoute
  '/problem': typeof ProblemRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solution': typeof SolutionRoute
  '/technology': typeof TechnologyRoute
  '/workflow': typeof WorkflowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/citizen': typeof CitizenRoute
  '/contact': typeof ContactRoute
  '/contractor': typeof ContractorRoute
  '/dashboard': typeof DashboardRoute
  '/government': typeof GovernmentRoute
  '/impact': typeof ImpactRoute
  '/problem': typeof ProblemRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solution': typeof SolutionRoute
  '/technology': typeof TechnologyRoute
  '/workflow': typeof WorkflowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/citizen'
    | '/contact'
    | '/contractor'
    | '/dashboard'
    | '/government'
    | '/impact'
    | '/problem'
    | '/sitemap.xml'
    | '/solution'
    | '/technology'
    | '/workflow'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/citizen'
    | '/contact'
    | '/contractor'
    | '/dashboard'
    | '/government'
    | '/impact'
    | '/problem'
    | '/sitemap.xml'
    | '/solution'
    | '/technology'
    | '/workflow'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/citizen'
    | '/contact'
    | '/contractor'
    | '/dashboard'
    | '/government'
    | '/impact'
    | '/problem'
    | '/sitemap.xml'
    | '/solution'
    | '/technology'
    | '/workflow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CitizenRoute: typeof CitizenRoute
  ContactRoute: typeof ContactRoute
  ContractorRoute: typeof ContractorRoute
  DashboardRoute: typeof DashboardRoute
  GovernmentRoute: typeof GovernmentRoute
  ImpactRoute: typeof ImpactRoute
  ProblemRoute: typeof ProblemRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolutionRoute: typeof SolutionRoute
  TechnologyRoute: typeof TechnologyRoute
  WorkflowRoute: typeof WorkflowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor': {
      id: '/contractor'
      path: '/contractor'
      fullPath: '/contractor'
      preLoaderRoute: typeof ContractorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government': {
      id: '/government'
      path: '/government'
      fullPath: '/government'
      preLoaderRoute: typeof GovernmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problem': {
      id: '/problem'
      path: '/problem'
      fullPath: '/problem'
      preLoaderRoute: typeof ProblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solution': {
      id: '/solution'
      path: '/solution'
      fullPath: '/solution'
      preLoaderRoute: typeof SolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CitizenRoute: CitizenRoute,
  ContactRoute: ContactRoute,
  ContractorRoute: ContractorRoute,
  DashboardRoute: DashboardRoute,
  GovernmentRoute: GovernmentRoute,
  ImpactRoute: ImpactRoute,
  ProblemRoute: ProblemRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolutionRoute: SolutionRoute,
  TechnologyRoute: TechnologyRoute,
  WorkflowRoute: WorkflowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
