/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AddSpaceRouteImport } from './routes/add-space'
import { Route as AiPricingRouteImport } from './routes/ai-pricing'
import { Route as AiRecommendationsRouteImport } from './routes/ai-recommendations'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as BookingConfirmedIdRouteImport } from './routes/booking-confirmed.$id'
import { Route as BookingIdRouteImport } from './routes/booking.$id'
import { Route as HostDashboardRouteImport } from './routes/host.dashboard'
import { Route as HostEarningsRouteImport } from './routes/host.earnings'
import { Route as HostManageBookingsRouteImport } from './routes/host.manage-bookings'
import { Route as HostManageListingsRouteImport } from './routes/host.manage-listings'
import { Route as SpaceIdRouteImport } from './routes/space.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AddSpaceRoute = AddSpaceRouteImport.update({
  id: '/add-space',
  path: '/add-space',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPricingRoute = AiPricingRouteImport.update({
  id: '/ai-pricing',
  path: '/ai-pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRecommendationsRoute = AiRecommendationsRouteImport.update({
  id: '/ai-recommendations',
  path: '/ai-recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmedIdRoute = BookingConfirmedIdRouteImport.update({
  id: '/booking-confirmed/$id',
  path: '/booking-confirmed/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingIdRoute = BookingIdRouteImport.update({
  id: '/booking/$id',
  path: '/booking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HostDashboardRoute = HostDashboardRouteImport.update({
  id: '/host/dashboard',
  path: '/host/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HostEarningsRoute = HostEarningsRouteImport.update({
  id: '/host/earnings',
  path: '/host/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const HostManageBookingsRoute = HostManageBookingsRouteImport.update({
  id: '/host/manage-bookings',
  path: '/host/manage-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const HostManageListingsRoute = HostManageListingsRouteImport.update({
  id: '/host/manage-listings',
  path: '/host/manage-listings',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceIdRoute = SpaceIdRouteImport.update({
  id: '/space/$id',
  path: '/space/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-space': typeof AddSpaceRoute
  '/ai-pricing': typeof AiPricingRoute
  '/ai-recommendations': typeof AiRecommendationsRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/booking-confirmed/$id': typeof BookingConfirmedIdRoute
  '/booking/$id': typeof BookingIdRoute
  '/host/dashboard': typeof HostDashboardRoute
  '/host/earnings': typeof HostEarningsRoute
  '/host/manage-bookings': typeof HostManageBookingsRoute
  '/host/manage-listings': typeof HostManageListingsRoute
  '/space/$id': typeof SpaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-space': typeof AddSpaceRoute
  '/ai-pricing': typeof AiPricingRoute
  '/ai-recommendations': typeof AiRecommendationsRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/booking-confirmed/$id': typeof BookingConfirmedIdRoute
  '/booking/$id': typeof BookingIdRoute
  '/host/dashboard': typeof HostDashboardRoute
  '/host/earnings': typeof HostEarningsRoute
  '/host/manage-bookings': typeof HostManageBookingsRoute
  '/host/manage-listings': typeof HostManageListingsRoute
  '/space/$id': typeof SpaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-space': typeof AddSpaceRoute
  '/ai-pricing': typeof AiPricingRoute
  '/ai-recommendations': typeof AiRecommendationsRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/booking-confirmed/$id': typeof BookingConfirmedIdRoute
  '/booking/$id': typeof BookingIdRoute
  '/host/dashboard': typeof HostDashboardRoute
  '/host/earnings': typeof HostEarningsRoute
  '/host/manage-bookings': typeof HostManageBookingsRoute
  '/host/manage-listings': typeof HostManageListingsRoute
  '/space/$id': typeof SpaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/add-space'
    | '/ai-pricing'
    | '/ai-recommendations'
    | '/browse'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/login'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/auth/callback'
    | '/booking-confirmed/$id'
    | '/booking/$id'
    | '/host/dashboard'
    | '/host/earnings'
    | '/host/manage-bookings'
    | '/host/manage-listings'
    | '/space/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/add-space'
    | '/ai-pricing'
    | '/ai-recommendations'
    | '/browse'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/login'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/auth/callback'
    | '/booking-confirmed/$id'
    | '/booking/$id'
    | '/host/dashboard'
    | '/host/earnings'
    | '/host/manage-bookings'
    | '/host/manage-listings'
    | '/space/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/add-space'
    | '/ai-pricing'
    | '/ai-recommendations'
    | '/browse'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/login'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/auth/callback'
    | '/booking-confirmed/$id'
    | '/booking/$id'
    | '/host/dashboard'
    | '/host/earnings'
    | '/host/manage-bookings'
    | '/host/manage-listings'
    | '/space/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AddSpaceRoute: typeof AddSpaceRoute
  AiPricingRoute: typeof AiPricingRoute
  AiRecommendationsRoute: typeof AiRecommendationsRoute
  BrowseRoute: typeof BrowseRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BookingConfirmedIdRoute: typeof BookingConfirmedIdRoute
  BookingIdRoute: typeof BookingIdRoute
  HostDashboardRoute: typeof HostDashboardRoute
  HostEarningsRoute: typeof HostEarningsRoute
  HostManageBookingsRoute: typeof HostManageBookingsRoute
  HostManageListingsRoute: typeof HostManageListingsRoute
  SpaceIdRoute: typeof SpaceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-space': {
      id: '/add-space'
      path: '/add-space'
      fullPath: '/add-space'
      preLoaderRoute: typeof AddSpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-pricing': {
      id: '/ai-pricing'
      path: '/ai-pricing'
      fullPath: '/ai-pricing'
      preLoaderRoute: typeof AiPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-recommendations': {
      id: '/ai-recommendations'
      path: '/ai-recommendations'
      fullPath: '/ai-recommendations'
      preLoaderRoute: typeof AiRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-confirmed/$id': {
      id: '/booking-confirmed/$id'
      path: '/booking-confirmed/$id'
      fullPath: '/booking-confirmed/$id'
      preLoaderRoute: typeof BookingConfirmedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$id': {
      id: '/booking/$id'
      path: '/booking/$id'
      fullPath: '/booking/$id'
      preLoaderRoute: typeof BookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/dashboard': {
      id: '/host/dashboard'
      path: '/host/dashboard'
      fullPath: '/host/dashboard'
      preLoaderRoute: typeof HostDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/earnings': {
      id: '/host/earnings'
      path: '/host/earnings'
      fullPath: '/host/earnings'
      preLoaderRoute: typeof HostEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/manage-bookings': {
      id: '/host/manage-bookings'
      path: '/host/manage-bookings'
      fullPath: '/host/manage-bookings'
      preLoaderRoute: typeof HostManageBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/manage-listings': {
      id: '/host/manage-listings'
      path: '/host/manage-listings'
      fullPath: '/host/manage-listings'
      preLoaderRoute: typeof HostManageListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/space/$id': {
      id: '/space/$id'
      path: '/space/$id'
      fullPath: '/space/$id'
      preLoaderRoute: typeof SpaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AddSpaceRoute: AddSpaceRoute,
  AiPricingRoute: AiPricingRoute,
  AiRecommendationsRoute: AiRecommendationsRoute,
  BrowseRoute: BrowseRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BookingConfirmedIdRoute: BookingConfirmedIdRoute,
  BookingIdRoute: BookingIdRoute,
  HostDashboardRoute: HostDashboardRoute,
  HostEarningsRoute: HostEarningsRoute,
  HostManageBookingsRoute: HostManageBookingsRoute,
  HostManageListingsRoute: HostManageListingsRoute,
  SpaceIdRoute: SpaceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
